version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: sqlite3:/app/db/development.sqlite3

  db:
    image: "ruby:3.2.2" # Use the same Ruby version as in your Dockerfile