# config/secrets.yml
development:
  secret_key_base: YOUR_DEVELOPMENT_SECRET_KEY

test:
  secret_key_base: YOUR_TEST_SECRET_KEY

production:
  secret_key_base: <%= Rails.application.credentials.production[:secret_key_base] %>
